<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_item = $this->getItem()?>
<tr>
    <td>
        <a href="<?php echo $this->getDeleteUrl() ?>">
            <img src="<?php echo $this->getSkinUrl('images/btn_trash.gif') ?>" width="16" height="16" alt="<?php $this->__('Remove item')?>" />
        </a>
    </td>
    <td>
        <a class="product-image" href="<?php echo $this->getProductUrl() ?>">
            <img src="<?php echo $this->getProductThumbnail()->resize(75); ?>" alt="<?php echo $this->htmlEscape($this->getProductName()) ?>" width="75" />
        </a>
    </td>
    <td>
        <h3 class="product-name"><a href="<?php echo $this->getProductUrl() ?>"><?php echo $this->getProductName() ?></a></h3>

        <?php if ($_attributes = $this->getProductAttributes()) :?>
        <ul>
            <?php foreach ($_attributes as $_attribute):?>
            <li>
                <strong><?php echo $_attribute['label']?>:</strong> <?php echo $_attribute['value']?>
            </li>
            <?php endforeach;?>
        </ul>
        <?php endif;?>

        <!-- item custom options -->
        <?php if ($_options = $this->getProductOptions()):?>
        <ul>
            <?php foreach ($_options as $_option):?>
            <?php
            $_randomId = str_replace('.', '_', '_' . microtime(true));
            $_truncatedRemainder = '';
            $_truncatedValue = Mage::helper('core/string')->truncate($_option['value'], 100, '', $_truncatedRemainder);
            $_truncatedValue     = nl2br($this->htmlEscape($_truncatedValue));
            $_truncatedRemainder = nl2br($this->htmlEscape($_truncatedRemainder));
            ?>
            <li id="<?php echo $_randomId?>" class="<?php if ($_truncatedRemainder):?>truncated<?php endif;?>">
                <strong><?php echo $_option['label'] ?>:</strong>
                <?php if ($_truncatedRemainder):?>
                    <?php echo $_truncatedValue?><span class="truncated-etc" id="<?php echo $_randomId?>_etc">...</span><span class="truncated-remainder" id="<?php echo $_randomId?>_remainder" style="display:none"><?php echo $_truncatedRemainder ?></span>
                    <script type="text/javascript">
                        Event.observe($('<?php echo $_randomId?>'), 'mouseover', function(){switchDisplay($('<?php echo $_randomId?>_etc'), $('<?php echo $_randomId?>_remainder'))});
                        Event.observe($('<?php echo $_randomId?>'), 'mouseout',  function(){switchDisplay($('<?php echo $_randomId?>_remainder'), $('<?php echo $_randomId?>_etc'))});
                    </script>
                <?php else:?>
                <?php echo $_truncatedValue?>
                <?php endif;?>
            </li>
            <?php endforeach;?>
        </ul>
        <?php endif;?>
        <!-- / -->

        <?php if ($messages = $this->getMessages()): ?>
        <?php foreach ($messages as $message): ?>
        <div class="shopping-cart-item-message <?php echo $message['type'] ?>">
            * <?php echo $message['text'] ?>
        </div>
        <?php endforeach; ?>
        <?php endif; ?>

    </td>
    <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
    <td>
        <input type="checkbox" value="1" name="cart[<?php echo $_item->getId() ?>][wishlist]" />
    </td>
    <?php endif ?>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getPriceInclTax($_item)); ?>
    </td>
    <?php endif; ?>
    <td>
        <input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getQty() ?>" size="4" class="input-text qty" maxlength="8" />
    </td>
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
    </td>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <td>
        <?php echo $this->helper('checkout')->formatPrice($this->helper('checkout')->getSubtotalInclTax($_item)); ?>
    </td>
    <?php endif; ?>
</tr>