<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Shopping cart template
 *
 * @see Mage_Checkout_Block_Cart
 */
?>
<div class="page-head-container">
    <h2 class="page-head"><?php echo $this->__('Shopping Cart') ?></h2>
</div>
<?php if(!$this->hasError()): ?>
<ul>
	<?php echo $this->getChildHtml('top_methods') ?>
</ul>
<?php endif; ?>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getUrl('checkout/cart/updatePost') ?>" method="post">
<table cellspacing="0" border="0" id="shopping-cart-table" class="data-table box-table shopping-cart">
    <col width="40" />
    <col width="75" />
    <col />
<?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
	<col width="1" />
<?php endif ?>
<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>
<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>
    <col width="1" />
<?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>
<?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
    <col width="80" />
<?php endif; ?>


<?php $mergedCells = ($this->helper('tax')->displayCartBothPrices() ? 2 : 1); ?>
    <thead>
        <tr>
            <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Remove') ?></th>
            <th rowspan="<?php echo $mergedCells; ?>">&nbsp;</th>
            <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Product Name') ?></th>
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
            <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Move to Wishlist') ?></th>
            <?php endif ?>
            <th colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Unit Price') ?></th>
            <th rowspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Qty') ?></th>
            <th colspan="<?php echo $mergedCells; ?>"><?php echo $this->__('Subtotal') ?></th>
        </tr>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
        <tr>
            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(false) ?></th>
            <th><?php echo $this->helper('tax')->getIncExcTaxLabel(true) ?></th>
        </tr>
        <?php endif; ?>
    </thead>
    <tfoot>
        <tr>
            <td colspan="100">
                <?php if($this->getContinueShoppingUrl()): ?>
                    <button class="form-button continue-shopping" onclick="setLocation('<?php echo $this->getContinueShoppingUrl() ?>')" type="button"><span><?php echo $this->__('Continue Shopping') ?></span></button>
                <?php endif; ?>
                <button class="form-button" type="submit"><span><?php echo $this->__('Update Shopping Cart') ?></span></button>
            </td>
        </tr>
    </tfoot>
    <tbody>
    <?php foreach($this->getItems() as $_item): ?>
        <?php echo $this->getItemHtml($_item) ?>
<?php
/*
        <tr>
            <td>
                <a href="<?php echo $this->getItemUrl($_item) ?>">
                    <img src="<?php echo $this->helper('catalog/image')->init($this->getItemProductForThumbnail($_item), 'thumbnail')->resize(75); ?>" alt="<?php echo $this->htmlEscape($this->getItemName($_item)) ?>" width="75" />
                </a>
            </td>
            <td>
                <h4><a href="<?php echo $this->getItemUrl($_item) ?>"><strong><?php echo $this->getItemName($_item) ?></strong></a></h4>
                <?php echo $this->getItemDescription($_item) ?>
                <?php if($_item->getMessage()): ?>
                <div style="font-size:95%;margin-top:6px;" class="shopping-cart-item-message <?php if($_item->getHasError()): ?>error<?php else: ?>notice<?php endif; ?>">
                    * <?php echo $_item->getMessage() ?>
                </div>
                <?php endif; ?>
            </td>
            <td>
                <a href="<?php echo $this->getItemDeleteUrl($_item) ?>">
                    <img src="<?php echo $this->getSkinUrl('images/btn_trash.gif') ?>" width="16" height="16" alt="Remove item" />
                </a>
            </td>
            <?php if ($this->helper('wishlist')->isAllowInCart()) : ?>
            <td>
                <input type="checkbox" value="1" name="cart[<?php echo $_item->getId() ?>][wishlist]" />
            </td>
            <?php endif ?>
            <td>
                <?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?>
            </td>
            <td>
                <input name="cart[<?php echo $_item->getId() ?>][qty]" value="<?php echo $this->getItemQty($_item) ?>" size="4" class="input-text qty" maxlength="8" />
            </td>
            <td>
                <?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?>
            </td>
        </tr>
*/
?>
    <?php endforeach ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('shopping-cart-table')</script>
</form>
<?php echo $this->getChildHtml('totals'); ?>

<script type="text/javascript">decorateTable('shoping-cart-totals-table')</script>
<?php if(!$this->hasError()): ?>
<ul class="checkout-types">
	<?php echo $this->getChildHtml('methods') ?>
</ul>
<?php endif; ?>

<?php echo $this->getChildHtml('coupon') ?>
<?php echo $this->getChildHtml('shipping') ?>
<?php echo $this->getChildHtml('crosssell') ?>




