<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head-container">
    <h2 class="page-head"><?php echo $this->__('Review Order') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" onsubmit="return showLoader();">
	<div class="box">
		<h3 class="box-head"><?php echo $this->__('Billing Information') ?></h3>
		<div class="col2-set">
			<div class="col-1">
				<?php $_address=$this->getBillingAddress() ?>
				<h4><?php echo $this->__('Billing Address') ?><span> | </span><a href="<?php echo $this->getEditBillingAddressUrl($_address) ?>"><?php echo $this->__('Change Billing Address') ?></a></h4>
				<address>
					<?php echo $_address->format('html') ?>
				</address>
			</div>
			<div class="col-2">
				<h4><?php echo $this->__('Payment Method') ?><span> | </span><a href="<?php echo $this->getEditBillingUrl() ?>"><?php echo $this->__('Change Payment Method') ?></a></h4>
				<input type="hidden" name="payment[cc_number]" value="<?php echo $this->htmlEscape($this->getPayment()->getCcNumber())?>" />
				<input type="hidden" name="payment[cc_cid]" value="<?php echo $this->htmlEscape($this->getPayment()->getCcCid())?>" />
				<?php echo $this->getPaymentHtml() ?>
			</div>
		</div>
	</div>

	<div class="box">
		<h3 class="box-head"><?php echo $this->__('Shipping Information') ?></h3>
		<?php foreach ($this->getShippingAddresses() as $_index => $_address): ?>
			<div class="col2-alt-set">
				<h4><?php echo $this->__('Address %s of %s', ($_index+1), $this->getShippingAddressCount()) ?></h4>
				<div class="col-1">
					<h5><?php echo $this->__('Shipping to') ?><span> | </span><a href="<?php echo $this->getEditShippingAddressUrl($_address) ?>"><?php echo $this->__('Change Shipping Address') ?></a></h5>
					<address>
						<?php echo $_address->format('html') ?>
					</address>
					<h5><?php echo $this->__('Shipping Method') ?><span> | </span><a href="<?php echo $this->getEditShippingUrl() ?>"><?php echo $this->__('Change Shipping Method') ?></a></h5>
					<?php if($_rate=$this->getShippingAddressRate($_address)): ?>
						<p><?php echo $_rate->getCarrierTitle() ?> (<?php echo $_rate->getMethodDescription() ?>) - <?php echo $_rate->getPrice() ?></p>
					<?php endif; ?>
				</div>
				<div class="col-2">
					<h5><?php echo $this->__('Items') ?><span> | </span><a href="<?php echo $this->getAddressesEditUrl() ?>"><?php echo $this->__('Edit Items') ?></a></h5>
					<table cellspacing="0" id="overview-table-<?php echo $_address->getId() ?>" class="data-table">
						<col />
						<col width="70" />
						<col width="30" />
						<col width="70" />
						<thead>
							<tr>
								<th><?php echo $this->__('Product Name') ?></th>
								<th><?php echo $this->__('Price') ?></th>
								<th><?php echo $this->__('Qty') ?></th>
								<th><?php echo $this->__('Subtotal') ?></th>
							</tr>
						</thead>
						<tbody>
						<?php foreach ($this->getShippingAddressItems($_address) as $_item): ?>
							<tr>
								<td>
									<?php echo $this->helper('checkout')->getQuoteItemProductName($_item) ?>
									<?php echo $this->helper('checkout')->getQuoteItemProductDescription($_item) ?>
								</td>
								<td><?php echo $this->helper('checkout')->formatPrice($_item->getCalculationPrice()) ?></td>
								<td><?php echo $_item->getQty()*1 ?></td>
								<td><?php echo $this->helper('checkout')->formatPrice($_item->getRowTotal()) ?></td>
							</tr>
						<?php endforeach; ?>
						</tbody>
						<tfoot>
						<?php foreach ($this->getShippingAddressTotals($_address) as $_total): ?>
							<tr>
								<td colspan="3"><?php echo $_total->getTitle() ?></td>
								<td><?php echo $this->helper('checkout')->formatPrice($_total->getValue()) ?></td>
							</tr>
						<?php endforeach; ?>
						</tfoot>
					</table>
					<script type="text/javascript">decorateTable('overview-table-<?php echo $_address->getId() ?>')</script>
				</div>
			</div>
			<?php if($this->getShippingAddressCount()!=$_index+1): ?>
			<?php endif; ?>
		<?php endforeach; ?>
	</div>
	<span id="review-please-wait" style="display:none;" class="opc-please-wait">
		<img src="<?php echo $this->getSkinUrl('images/opc-ajax-loader.gif') ?>" alt="" /> &nbsp; <?php echo $this->__('Submitting order information...') ?> &nbsp;
	</span>
	<p><big><?php echo $this->__('Grand Total:') ?> <?php echo $this->helper('checkout')->formatPrice($this->getTotal()) ?></big></p>
	<span id="review-buttons-container">
		<button class="form-button" id="review-button" type="submit"><span><?php echo $this->__('Place Order') ?></span></button>
	</span>

	<div class="buttons-container">
		<a href="<?php echo $this->getBackUrl() ?>" class="back-link"><?php echo $this->__('&laquo; Back to Billing Information') ?></a>
	</div>
</form>

<script type="text/javascript">
    var submitted = false;

    function showLoader()
    {
        if (submitted) {
            return false;
        }
        submitted = true;
        var step='review';
        Element.show(step+'-please-wait');
        $(step+'-buttons-container').setStyle({opacity:.5});
        return true;
    }
</script>
