<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $parentItem = $this->getItem() ?>
<?php $items = array_merge(array($parentItem), $parentItem->getChildrenItems()); ?>
<?php $_count = count ($items) ?>
<?php $_index = 0 ?>
<?php $bundleOptions = $this->getBundleOptions() ?>

<?php $_prevOptionLabel = '' ?>

<?php foreach ($items as $_item): ?>

<?php if (empty($_option['value'])): ?>
    <?php $_option = array_shift($bundleOptions); ?>
<?php endif; ?>

<?php if($this->getItemOptions() || $parentItem->getDescription() || $this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php if ($_item->getParentItem()): ?>
    <?php if ($_prevOptionLabel != $_option['label']): ?>
    <tr class="<?php if ($_item->getLastRow()) echo 'last';?>">
        <td class="indent"><strong><?php echo $_option['label'] ?></strong></td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
    </tr>
    <?php $_prevOptionLabel = $_option['label'] ?>
    <?php endif; ?>
<?php endif; ?>
<tr class="<?php echo (++$_index==$_count && !$_showlastRow)?'border':'' ?>" id="order-item-row-<?php echo $_item->getId() ?>">

    <?php if (!$_item->getParentItem()): ?>
    <td>
        <?php echo $this->htmlEscape($_item->getName()) ?>
    </td>
    <?php else: ?>
    <td class="indent">
        <?php if (is_array($_option['value'])): ?>
            <?php echo $this->getValueHtml(array_shift($_option['value']))?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <?php endif; ?>
    <td class="nowrap"><?php echo $_item->getSku() ?></td>
    <td class="a-right">
        <?php if (!$_item->getParentItem()): ?>
            <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceExclTax()): ?>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <?php echo Mage::helper('sales')->__('Excl. Tax'); ?>:
                <?php endif; ?>
                <strong><?php echo $this->getOrder()->formatPrice($this->getItem()->getPrice()) ?></strong><br />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceInclTax()): ?>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <?php echo Mage::helper('sales')->__('Incl. Tax'); ?>:
                <?php endif; ?>
                <strong><?php echo $this->getOrder()->formatPrice($this->helper('checkout')->getPriceInclTax($this->getItem())); ?></strong>
            <?php endif; ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <td class="a-right nowrap">
        <?php if (($_item->getParentItem() && $this->isChildCalculated()) ||
                (!$_item->getParentItem() && !$this->isChildCalculated())): ?>
            <?php if ($_item->getQtyOrdered() > 0): ?>
                <?php echo Mage::helper('sales')->__('Ordered'); ?>: <strong><?php echo $_item->getQtyOrdered()*1 ?></strong><br />
            <?php endif; ?>
            <?php if ($_item->getQtyShipped() > 0 && !$this->isShipmentSeparately()): ?>
                <?php echo Mage::helper('sales')->__('Shipped'); ?>: <strong><?php echo $_item->getQtyShipped()*1 ?></strong><br />
            <?php endif; ?>
            <?php if ($_item->getQtyCanceled() > 0): ?>
                <?php echo Mage::helper('sales')->__('Canceled'); ?>: <strong><?php echo $_item->getQtyCanceled()*1 ?></strong><br />
            <?php endif; ?>
            <?php if ($_item->getQtyRefunded() > 0): ?>
                <?php echo Mage::helper('sales')->__('Refunded'); ?>: <strong><?php echo $_item->getQtyRefunded()*1 ?></strong>
            <?php endif; ?>
        <?php elseif ($_item->getQtyShipped() > 0 && $_item->getParentItem() && $this->isShipmentSeparately()): ?>
            <?php echo Mage::helper('sales')->__('Shipped'); ?>: <strong><?php echo $_item->getQtyShipped()*1 ?></strong>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <td class="a-right">
        <?php if (!$_item->getParentItem()): ?>
            <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceExclTax()): ?>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <?php echo Mage::helper('sales')->__('Excl. Tax'); ?>:
                <?php endif; ?>
                <strong><?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?></strong><br />
            <?php endif; ?>
            <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceInclTax()): ?>
                <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                    <?php echo Mage::helper('sales')->__('Incl. Tax'); ?>:
                <?php endif; ?>
                <strong><?php echo $this->getOrder()->formatPrice($this->helper('checkout')->getSubtotalInclTax($this->getItem())); ?></strong>
            <?php endif; ?>
        <?php else: ?>
            &nbsp;
        <?php endif; ?>
    </td>
    <!--
    <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceExclTax()): ?>
    <th class="nowrap a-right" width="5%"><?php echo $this->getOrder()->formatPrice($this->getItem()->getRowTotal()) ?></th>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartBothPrices() || $this->helper('tax')->displayCartPriceInclTax()): ?>
    <th class="nowrap a-right" width="5%"><?php echo $this->getOrder()->formatPrice($this->helper('checkout')->getSubtotalInclTax($this->getItem())); ?></th>
    <?php endif; ?>
    -->
</tr>
<?php endforeach; ?>

<?php if ($_showlastRow): ?>
<tr class="border">
    <td class="indent">
        <?php if($_options = $this->getItemOptions()): ?>
        <ul class="item-options-bundle">
        <?php foreach ($_options as $_option): ?>
            <li><strong><?php echo $this->htmlEscape($_option['label']) ?>:</strong><br />
                <?php echo $this->htmlEscape($_option['value']); ?>
            </li>
        <?php endforeach; ?>
        </ul>
        <?php endif; ?>
        <?php echo $_item->getDescription() ?>
        <?php if($this->helper('giftmessage/message')->getIsMessagesAvailable('order_item', $parentItem) && $parentItem->getGiftMessageId()): ?>
            <br /><a href="#" id="order-item-gift-message-link-<?php echo $parentItem->getId() ?>" class="giftmessage-preview-link expand" onclick="return giftMessageToogle('<?php echo $parentItem->getId() ?>')"><?php echo Mage::helper('sales')->__('Gift Message') ?></a>
        <?php endif; ?>
    </td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
</tr>
<?php endif; ?>