<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_order = $this->getOrder() ?>
<div class="grid hor-scroll">
    <table cellspacing="0" class="data-bundle">
        <col />
        <col width="70" />
        <col width="80" />
        <col width="80" />
        <col width="100" />
        <col width="90" />
        <col width="90" />
        <col width="100" />
        <col width="100" />
        <thead>
            <tr class="headings">
                <th><?php echo $this->helper('sales')->__('Product') ?></th>
                <th><?php echo $this->helper('sales')->__('Item Status') ?></th>
                <th><?php echo $this->helper('sales')->__('Original Price') ?></th>
                <th><?php echo $this->helper('sales')->__('Price') ?></th>
                <th><?php echo $this->helper('sales')->__('Qty') ?></th>
                <th><?php echo $this->helper('sales')->__('Subtotal') ?></th>
                <th><?php echo $this->helper('sales')->__('Tax Amount') ?></th>
                <th><?php echo $this->helper('sales')->__('Tax Percent') ?></th>
                <th><?php echo $this->helper('sales')->__('Discount Amount') ?></th>
                <th class="last"><?php echo $this->helper('sales')->__('Row Total') ?></th>
            </tr>
        </thead>
        <?php $_items = $this->getItemsCollection() ?>
        <?php $i=0;foreach ($_items as $_item):?>
            <?php if ($_item->getParentItem()) continue; else $i++;?>
            <tbody class="<?php echo $i%2?'even':'odd' ?>">
                <?php echo $this->getItemHtml($_item) ?>
            </tbody>
        <?php endforeach; ?>
    </table>
</div>
