<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_item = $this->getItem() ?>
<?php $this->setPriceDataObject($_item); ?>
<tr class="border">
    <td>
        <?php echo $this->getColumnHtml($_item, 'name') ?>
    </td>
    <td class="price">
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <?php echo $this->helper('tax')->__('Excl. Tax'); ?>
        <?php endif; ?>
        <?php echo $this->displayPriceAttribute('price') ?>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <br />
            <?php echo $this->helper('tax')->__('Incl. Tax'); ?>
        <?php endif; ?>
        <?php echo $this->displayPriceInclTax($_item); ?>
    <?php endif; ?>
    </td>
    <td><?php echo $this->getColumnHtml($_item, 'qty') ?></td>
    <?php if ($this->canReturnToStock()) : ?>
        <td class="a-center"><input type="checkbox" name="creditmemo[items][<?php echo $_item->getOrderItemId() ?>][back_to_stock]" value="1"<?php if ($_item->getBackToStock()):?> checked<?php endif;?>/></td>
    <?php endif; ?>
    <td class="a-center">
    <?php if ($this->canEditQty()) : ?>
        <input type="text" class="input-text qty-input" name="creditmemo[items][<?php echo $_item->getOrderItemId() ?>][qty]" value="<?php echo $_item->getQty()*1 ?>"/>
    <?php else : ?>
        <?php echo $this->getQty()*1 ?>
    <?php endif; ?>
    </td>
    <td class="price">
    <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <?php echo $this->helper('tax')->__('Excl. Tax'); ?>
        <?php endif; ?>
        <?php echo $this->displayPriceAttribute('row_total') ?>
    <?php endif; ?>
    <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
        <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
            <br />
            <?php echo $this->helper('tax')->__('Incl. Tax'); ?>
        <?php endif; ?>
        <?php echo $this->displaySubtotalInclTax($_item); ?>
    <?php endif; ?>
    </td>
    <td class="price"><?php echo $this->displayPriceAttribute('tax_amount') ?></td>
    <td class="price"><?php echo $this->displayPriceAttribute('discount_amount') ?></td>
    <td class="last price">
        <?php echo $this->displayPrices(
            $_item->getBaseRowTotal()+$_item->getBaseTaxAmount()-$_item->getBaseDiscountAmount(),
            $_item->getRowTotal()+$_item->getTaxAmount()-$_item->getDiscountAmount()
        ) ?>
    </td>
</tr>