<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_item = $this->getItem() ?>
<?php $items = $this->getChilds($_item); ?>
<?php $_count = count ($items) ?>
<?php $_index = 0 ?>
<?php $bundleOptions = $this->getBundleOptions($this->getItem()->getOrderItem()) ?>
<?php $_prevOptionLabel = '' ?>

<?php if($this->getOrderOptions() || $_item->getDescription()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php $this->setPriceDataObject($_item) ?>
    <?php if (empty($_option['value'])): ?>
        <?php $_option = array_shift($bundleOptions); ?>
    <?php endif; ?>
    <?php if ($_item->getOrderItem()->getParentItem()): ?>
        <?php if ($_prevOptionLabel != $_option['label']): ?>
        <tr>
            <td class="indent">
                <strong><?php echo $_option['label'] ?></strong>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last"></td>
        </tr>
        <?php $_prevOptionLabel = $_option['label'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr class="<?php echo (++$_index==$_count && !$_showlastRow)?'border':'' ?>">
        <?php if (!$_item->getOrderItem()->getParentItem()): ?>
        <td>
            <div><?php echo $this->htmlEscape($_item->getName()) ?></div>
            <div class="nobr"><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo $_item->getSku() ?></div>
        </td>
        <?php else: ?>
        <td class="indent">
            <?php echo $this->getValueHtml(array_shift($_option['value']), $_item)?>
        </td>
        <?php endif; ?>
        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <?php echo $this->helper('tax')->__('Excl. Tax'); ?>
                    <?php endif; ?>
                    <?php echo $this->displayPriceAttribute('price') ?>
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <br />
                        <?php echo $this->helper('tax')->__('Incl. Tax'); ?>
                    <?php endif; ?>
                    <?php echo $this->displayPriceInclTax($_item); ?>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <td>
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $_item->getQty()*1 ?>
            <?php endif; ?>
        </td>
        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <?php echo $this->helper('tax')->__('Excl. Tax'); ?>
                    <?php endif; ?>
                    <?php echo $this->displayPriceAttribute('row_total') ?>
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <br />
                        <?php echo $this->helper('tax')->__('Incl. Tax'); ?>
                    <?php endif; ?>
                    <?php echo $this->displaySubtotalInclTax($_item); ?>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('tax_amount') ?>
            <?php endif; ?>
        </td>
        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('discount_amount') ?>
            <?php endif; ?>
        </td>
        <td class="price last">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPrices(
                    $_item->getBaseRowTotal()-$_item->getBaseDiscountAmount()+$_item->getBaseTaxAmount(),
                    $_item->getRowTotal()-$_item->getDiscountAmount()+$_item->getTaxAmount()
                ) ?>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if($_showlastRow): ?>
    <tr class="border">
        <td class="indent">
            <?php if ($this->getOrderOptions()): ?>
                <ul class="item-options-bundle">
                <?php foreach ($this->getOrderOptions() as $option): ?>
                    <li><strong><?php echo $option['label'] ?>:</strong><br />
                        <?php echo $this->htmlEscape($option['value']); ?>
                    </li>
                <?php endforeach; ?>
                </ul>
            <?php endif; ?>
            <?php echo $this->getItem()->getDescription() ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last"></td>
    </tr>
<?php endif; ?>
