<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>
<?php $_product = $this->getProduct() ?>
<?php $_options = $this->getOptions() ?>

<?php echo $this->getPriceHtml($_product) ?>

<script type="text/javascript">
var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
</script>

<?php if($_product->isSaleable()): ?>

<?php /* @see bundle/options.phtml */ ?>

    <?php $_tierPrices = $this->getTierPrices() ?>
    <?php if(count($_tierPrices)>0): ?>
    <div class="product-pricing">
        <ul class="bare">
        <?php foreach($_tierPrices as $_price): ?>
            <li>
                <?php echo $this->__('Buy %s with %s%% discount each', $_price['price_qty'], $_price['price']*1) ?>
            </li>
        <?php endforeach ?>
        </ul>
    </div>
    <?php endif; ?>

    <p><small><?php echo $this->__('Availability: In stock.') ?></small></p>

    <?php $_finalPrice = Mage::helper('tax')->getPrice($_product, $_product->getFinalPrice()); ?>
    <?php $_finalPriceInclTax = Mage::helper('tax')->getPrice($_product, $_product->getFinalPrice(), true); ?>

    <?php if ($this->helper('tax')->displayBothPrices()): ?>
        <span class="price-excluding-tax">
            <span class="label"><?php echo $this->__('Excl. Tax:') ?></span>
            <span class="price" id="price-excluding-tax-<?php echo $_product->getId() ?>">
                <?php echo Mage::helper('core')->currency($_finalPrice) ?>
            </span>
        </span>
        <span class="price-including-tax">
            <span class="label"><?php echo $this->__('Incl. Tax:') ?></span>
            <span class="price" id="price-including-tax-<?php echo $_product->getId() ?>">
                <?php echo Mage::helper('core')->currency($_finalPriceInclTax) ?>
            </span>
        </span>
    <?php else: ?>
    <span class="regular-price" id="product-price-<?php echo $_product->getId() ?>">
        <?php echo Mage::helper('core')->currency($_finalPrice) ?>
    </span>
    <?php endif; ?>

    <br />
    <br />
<?php else: ?>
    <p><small><?php echo $this->__('Availability: Out of stock.') ?></small></p>
<?php endif; ?>

<?php if($_product->isSaleable()): ?>
    <fieldset class="add-to-cart-box">
        <legend><?php echo $this->__('Add Items to Cart') ?></legend>
        <span class="qty-box"><label for="qty"><?php echo $this->__('Qty') ?>:</label>
        <input name="qty" type="text" class="input-text qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" /></span>
        <button class="form-button" onclick="productAddToCartForm.submit()"><span><?php echo $this->__('Add to Cart') ?></span></button>
        <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
            <strong><?php echo $this->__('OR') ?></strong>
        <?php endif; ?>
    </fieldset>
<?php endif; ?>

<div class="add-to-box">
<?php if ($this->helper('wishlist')->isAllow()) : ?>
    <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a><br/>
<?php endif; ?>

<?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ): ?>
    <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
<?php endif; ?>
</div>

<script type="text/javascript">decorateTable('super-product-table')</script>