<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php
$_product = $this->getProduct();
$_options = $this->getOptions();
?>

<?php if($_product->isSaleable()):?>
    <?php if (count($_options)): ?>
    <dl>
    <?php foreach ($_options as $_option): ?>
        <?php if (!$_option->getSelections()): ?>
            <?php continue; ?>
        <?php endif; ?>
        <?php echo $this->getOptionHtml($_option) ?>
    <?php endforeach; ?>
    </dl>
    <?php else: ?>
        <p><?php echo $this->__('No options of this product are available.') ?></p>
    <?php endif; ?>

<?php /*
    <table cellspacing="0" class="data-table bundle-product" id="super-product-table">
        <thead>
            <tr>
                <th><?php echo $this->__('Option') ?></th>
                <th><?php echo $this->__('Selection') ?></th>
                <th class="a-center"><?php echo $this->__('Qty') ?></th>
            </tr>
        </thead>
        <tbody>
        <?php if (count($_options)): ?>
        <?php foreach ($_options as $_option): ?>
            <?php if (!$_option->getSelections()): ?>
                <?php continue; ?>
            <?php endif; ?>
            <?php echo $this->getOptionHtml($_option) ?>
        <?php endforeach; ?>
        <?php else: ?>
            <tr>
                <td colspan="<?php if ($_product->isSaleable()): ?>3<?php else: ?>2<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
            </tr>
        <?php endif; ?>
        </tbody>
    </table>
*/ ?>

<?php endif;?>