<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="padder">
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<?php $product=$_product=$this->getProduct() ?>

        <div class="product-img-box">
            <?php if ($_product->getImage() != 'no_selection' && $_product->getImage()): ?>
            <p class="main-product-img">
                <img id="image" src="<?php echo $this->helper('catalog/image')->init($_product, 'image'); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
            </p>
            <p class="a-center">Double click on above image to view full picture</p>
            <div class="image-zoom" id="track_outer">
                <img id="zoom_out" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_out.gif') ?>" alt="<?php echo $this->__('Zoom Out') ?>" class="btn-zoom-out"/>
                <div id="track">
                    <div id="handle"></div>
                </div>
                <img id="zoom_in" src="<?php echo $this->getSkinUrl('images/slider_btn_zoom_in.gif') ?>" alt="<?php echo $this->__('Zoom In') ?>" class="btn-zoom-in"/>
            </div>
            <script type="text/javascript">
                Event.observe(window, 'load', function() {
                    product_zoom = new Product.Zoom('image', 'track', 'handle', 'zoom_in', 'zoom_out');
                });
            </script>
            <?php else: ?>
            <img id="image" src="<?php echo $this->helper('catalog/image')->init($_product, 'image')->resize(265); ?>" alt="<?php echo $this->htmlEscape($_product->getName()) ?>"/>
            <?php endif; ?>
        </div>
        <div class="product-info-box">
            <h3 class="product-name"><?php echo $this->htmlEscape($product->getName()) ?></h3>
        <?php echo $this->getChildHtml('rating') ?>
        <?php if( $reviewCount ): ?>
            <a href="#customer-reviews" class="no-wrap"><?php echo $this->__('%s Review(s)', $reviewCount) ?></a>
        <?php endif; ?>

        <form action="<?php echo $this->getUrl('checkout/cart/add') ?>" method="post" id="product_addtocart_form">
        <fieldset>
        <input type="hidden" name="product" value="<?php echo $product->getId() ?>"/>
        </fieldset>

        <?php if($product->isSuperConfig()): ?>
        <?php echo $this->getChildHtml('super_config') ?>
        <?php endif; ?>
        <?php $_tierPrices = $this->getTierPrices($product) ?>
        <?php if(count($_tierPrices)>0): ?>
            <div class="product-pricing">
                <ul class="bare">
                <?php foreach($_tierPrices as $_price): ?>
                    <li><?php echo $this->__('Buy %s for %s', $_price['price_qty'], $_price['formated_price']) ?></li>
                <?php endforeach ?>
                </ul>
            </div>
        <?php endif; ?>

        <?php if($product->isGrouped()): ?>
            <?php echo $this->getChildHtml('super_group') ?>
        <?php endif; ?>

        <?php if(!$product->isGrouped()): ?>
            <?php if($product->isSaleable()): ?>
            <p><?php echo $this->__('Availability: In stock.') ?></p>
            <?php else: ?>
            <p><?php echo $this->__('Availability: Out of stock.') ?></small></p>
            <?php endif; ?>

            <?php if($product->isSaleable()): ?>
            <?php echo $this->getPriceHtml($product) ?>
            <fieldset class="add-to-cart-box">
                <legend><?php echo $this->__('Add Items to Cart') ?></legend>
                <div class="f-left">
                    <span class="qty-box"><label for="qty"><?php echo $this->__('Qty') ?>:</label>
                    <input name="qty" type="text" class="input-text qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>"/></span>
                    <a href="#" onclick="productAddToCartForm.submit()"><img src="<?php echo $this->getSkinUrl('images/btn_add_to_cart.gif');?>" alt="<?php echo $this->__('Add to Cart') ?>" class="v-middle" style="margin:0 10px 0 5px;"/></a>
                </div>
            <?php if ($this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ) : ?>
                <ul class="add-to f-left">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ): ?>
                    <li><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                <?php endif; ?>
            </ul>
            <?php endif; ?>
            </fieldset>


            <?php else: ?>
            <fieldset class="add-to-cart-box">
            <?php if ($this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ) : ?>
                <ul class="add-to">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $wishlistLink ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ): ?>
                    <li><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                <?php endif; ?>
            </ul>
            <?php endif; ?>

            </fieldset>
            <?php endif; ?>


        <?php else: ?>
            <fieldset class="add-to-cart-box">
            <a href="#" onclick="productAddToCartForm.submit()"><img src="<?php echo $this->getSkinUrl('images/btn_add_to_cart.gif');?>" alt="<?php echo $this->__('Add to Cart') ?>" class="v-middle" style="margin:0 10px 0 5px;"/></a>
            
            <?php if ($this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ) : ?>
                <ul class="add-to">
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                    <li><a href="<?php echo $wishlistLink ?>"><?php echo $this->__('Add to Wishlist') ?></a></li>
                <?php endif; ?>
                <?php if($_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product) ): ?>
                    <li><a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a></li>
                <?php endif; ?>
            </ul>
            <?php endif; ?>
            </fieldset>
        <?php endif; ?>
        </form>
        <script type="text/javascript">
            var productAddToCartForm = new VarienForm('product_addtocart_form');
            productAddToCartForm.submit = function() {
                if(this.validator.validate()) {
                    this.form.submit();
                }
            }.bind(productAddToCartForm);
        </script>

        <p><a href="<?php echo $product->getProductUrl() ?>">&laquo; <?php echo $this->__('Back to Main Product Info') ?></a></p>

        </div>
        <div class="clear"></div>
    </div>

<br/>

    <?php if( $this->getCollection() && $this->count()): ?>
            <div class="head head-alt2" id="customer-reviews">
                <h4 class="title"><?php echo $this->__('Customer Reviews') ?></h4>
            </div>
            <div class="padder">
            <ol>
        <?php foreach( $this->getCollection()->getItems() as $_review ): ?>
                <li>
                    <a href="<?php echo $this->getReviewUrl($_review->getId()) ?>"><strong><?php echo $this->htmlEscape($_review->getTitle()) ?></strong></a> <?php echo $this->__('Review by %s', $this->htmlEscape($_review->getNickname())) ?>
                    <table class="ratings-list" cellspacing="0">
                        <tbody>
                        <?php foreach( $_review->getRatingVotes() as $_vote ): ?>
                        <tr>
                            <td class="label"><strong><?php echo $_vote->getRatingCode() ?></strong></td>
                            <td>
                                <div class="rating-box">
                                    <div class="rating" style="width: <?php echo $_vote->getPercent() ?>%;"></div>
                                </div>
                            </td>
                        </tr>
                        <?php endforeach; ?>
                        </tbody>
                    </table>
                    <p><?php echo nl2br($this->htmlEscape($_review->getDetail())) ?> <?php echo $this->__('(Posted on %s)', $this->formatDate($_review->getCreatedAt()), 'long') ?></p>
                </li>
        <?php endforeach; ?>
            </ol>
            </div>
        <?php echo $this->getToolbarHtml() ?>
    <?php else: ?>
    <?php endif; ?>
    <div class="padder"><br/>
    <?php echo $this->getChildHtml('reviewForm') ?>
    </div>