<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Product list template
 *
 * @see Mage_Catalog_Block_Product_List
 */
?>
<?php $_productCollection=$this->getLoadedProductCollection() ?>
<?php if(!$_productCollection->count()): ?>
<p class="note-msg"><?php echo $this->__('There are no products matching the selection.') ?></p>
<?php else: ?>
<div class="category-products">
	<h3><?php echo $this->__('Category Products:') ?></h3>
	<?php echo $this->getToolbarHtml() ?>

	<?php // List mode ?>
	<?php if($this->getMode()!='grid'): ?>
	<?php $_iterator = 0; ?>
	<ul class="products-list">
	<?php foreach ($_productCollection as $_product): ?>
		<li class="item<?php if( ++$_iterator == sizeof($_productCollection) ): ?> last<?php endif; ?>">
	        <?php // Product Image ?>
			<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
				<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135, 135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
			</a>

	        <?php // Product description ?>
	        <div class="product-shop">
	            <h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName())?></a></h4>
	            <?php if($_product->getRatingSummary()): ?>
	            <?php echo $this->getReviewsSummaryHtml($_product) ?>
	            <?php endif; ?>
	            <?php echo $this->getPriceHtml($_product, true) ?>
	            <?php if($_product->isSaleable()): ?>
	            <button class="form-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
	            <?php else: ?>
	            <p><small><?php echo $this->__('Out of stock') ?></small></p>
	            <?php endif; ?>
	            <p>
	                <?php echo nl2br($_product->getShortDescription()) ?>
	                <a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->__('Learn More') ?></a>
	            </p>
	            <p>
	                <?php if ($this->helper('wishlist')->isAllow()) : ?>
	                <a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
	                <?php endif; ?>
	                <?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?><br />
	                <a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
	                <?php endif; ?>
	            </p>
	        </div>
		</li>
	<?php endforeach; ?>
	</ul>

	<?php else: ?>

	<?php // Grid Mode ?>

	<?php $_collectionSize = $_productCollection->count() ?>
	<table cellspacing="0" class="products-grid" id="product-grid-table">
	<?php $i=0; foreach ($_productCollection as $_product): ?>
		<?php if ($i++%3==0): ?>
		<tr>
		<?php endif ?>
			<td>
				<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
					<img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(135, 135); ?>" width="135" height="135" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
				</a>
				<h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>"><?php echo $this->htmlEscape($_product->getName()) ?></a></h4>
				<?php if($_product->getRatingSummary()): ?>
				<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
				<?php endif; ?>
				<?php echo $this->getPriceHtml($_product, true) ?>
				<?php if($_product->isSaleable()): ?>
				<button class="form-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
				<?php else: ?>
				<p><small><?php echo $this->__('Out of stock') ?></small></p>
				<?php endif; ?>
				<p>
					<?php if ($this->helper('wishlist')->isAllow()) : ?>
					<a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
					<?php endif; ?>
					<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?><br />
					<a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
					<?php endif; ?>
				</p>
			</td>
		<?php if ($i%3==0 && $i!=$_collectionSize): ?>
		</tr>
		<?php endif ?>
		<?php endforeach ?>
		<?php for($i;$i%3!=0;$i++): ?>
			  <td>&nbsp;</td>
		<?php endfor ?>
		<?php if ($i%3==0): ?>
		</tr>
		<?php endif ?>
	</table>
	<script type="text/javascript">decorateTable('product-grid-table')</script>

	<?php endif; ?>
	<?php echo $this->getToolbarHtml() ?>
</div>
<?php endif; ?>