<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<?php $_product=$this->getProduct() ?>
<div class="product-info-box">
    <div class="product-essential">

        <div class="product-shop">
            <h2 class="product-name"><?php echo $this->htmlEscape($_product->getName()) ?></h2>

            <?php if ($this->canEmailToFriend()): ?>
                <p><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></p>
            <?php endif; ?>

            <?php echo $this->getReviewsSummaryHtml($_product, false, true)?>

            <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form">
                <fieldset>
                    <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
                    <input type="hidden" name="related_product" id="related-products-field" value="" />
                </fieldset>

                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('product_type_data') ?>

                <?php if (!$this->hasOptions()):?>
                    <?php echo $this->getChildHtml('tierprices') ?>
                    <div class="add-to-holder">
                        <?php if($_product->isSaleable()): ?>
                            <?php echo $this->getChildHtml('addtocart') ?>
                            <?php if( $this->helper('wishlist')->isAllow() || $_compareUrl=$this->helper('catalog/product_compare')->getAddUrl($_product)): ?>
                                <span class="add-or"><?php echo $this->__('OR') ?></span>
                            <?php endif; ?>
                        <?php endif; ?>
                        <?php echo $this->getChildHtml('addto') ?>
                    </div>
                <?php else:?>
                    <?php echo $this->getChildHtml('addto') ?>
                <?php endif; ?>

                <div class="divider"></div>
                <h3><?php echo $this->__('Quick Overview') ?></h3>
                <p><?php echo nl2br($_product->getShortDescription()) ?></p>

                <?php if ($this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container1', '', true, true) ?>
                <?php endif;?>

                <?php if ($this->hasOptions()):?>
                    <?php echo $this->getChildChildHtml('container2', '', true, true) ?>
                <?php endif;?>
            </form>

            <script type="text/javascript">
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function() {
                    if(this.validator.validate()) {
                        this.form.submit();
                    }
                }.bind(productAddToCartForm);
            </script>
        </div>

        <div class="product-media">
            <?php echo $this->getChildHtml('media') ?>
        </div>

    </div>

    <div class="product-collateral">
        <h3><?php echo $this->__('Product Description') ?></h3>
        <?php echo $this->getChildHtml('description') ?>

        <?php if($_additional = $this->getChildHtml('additional')): ?>
            <h3><?php echo $this->__('Additional Information') ?></h3>
            <?php echo $_additional ?>
        <?php endif; ?>

        <?php echo $this->getChildHtml('upsell_products') ?>
        <?php echo $this->getChildHtml('product_additional_data') ?>
    </div>
</div>
