<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/**
 * Customer login form template
 *
 * @see Mage_Customer_Block_Form_Login
 */
?>
<div class="page-head-container">
    <h2 class="page-head"><?php echo $this->__('Login or Create an Account') ?></h2>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="login-form">
<div class="box">
	<h3 class="box-head"><?php echo $this->__('New Customers') ?></h3>
	<p><?php echo $this->__('By creating an account with our store, you will be able to move through the checkout process faster, store multiple shipping addresses, view and track your orders in your account and more.') ?></p>
	<div class="buttons-container">
		<button class="form-button" onclick="window.location='<?php echo $this->getCreateAccountUrl() ?>';" type="button"><span><?php echo $this->__('Create an Account') ?></span></button>
	</div>
</div>
<div class="box">
	<h3 class="box-head"><?php echo $this->__('Registered Customers') ?></h3>
	<p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
	<ul class="form-list">
		<li>
			<label for="email"><?php echo $this->__('Email Address') ?> <span class="required">*</span></label><br />
			<input name="login[username]" value="<?php echo $this->htmlEscape($this->getUsername()) ?>" title="<?php echo $this->__('Email Address') ?>" id="email" type="text" class="input-text required-entry" style="width:250px;" />
		</li>
		<li>
			<label for="pass"><?php echo $this->__('Password') ?> <span class="required">*</span></label><br />
			<input name="login[password]" type="password" class="input-text required-entry validate-password" id="pass" style="width:250px;" />
		</li>
	</ul>
	<p class="required"><?php echo $this->__('* Required Fields') ?></p>
	<div class="buttons-container">
		<a href="<?php echo $this->getForgotPasswordUrl() ?>"><?php echo $this->__('Forgot Your Password?') ?></a>
		<button class="form-button" type="submit" name="send" id="send2"><span><?php echo $this->__('Login') ?></span></button>
	</div>
</div>
</form>
<script type="text/javascript">
    var dataForm = new VarienForm('login-form', true);
</script>