<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php  $_order = $this->getOrder() ?>
<a href="<?php echo $this->getPrintAllInvoicesUrl($_order) ?>" target="_blank"><?php echo $this->__('Print All Invoices') ?></a>
<?php foreach ($_order->getInvoiceCollection() as $_invoice): ?>
<br />
<div class="head">
    <h3><?php echo $this->__('Invoice #') ?><?php echo $_invoice->getIncrementId(); ?></h3>
    <a href="<?php echo $this->getPrintInvoiceUrl($_invoice) ?>" target="_blank"><?php echo $this->__('Print Invoice') ?></a>
</div>
<h4><?php echo $this->__('Items Invoiced') ?></h4><table cellspacing="0" class="data-table data-bundle" id="my-orders-table-<?php echo $_invoice->getId(); ?>">
    <col />
    <col width="15%" />
    <col width="10%" />
    <col width="20%" />
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th width="10%" class="a-center"><?php echo $this->__('SKU') ?></th>
            <th width="10%" class="a-center"><?php echo $this->__('Price') ?></th>
            <th class="a-center" width="10%"><?php echo $this->__('Qty Invoiced') ?></th>
            <th class="a-center" width="15%"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
        <?php $_items = $_invoice->getAllItems(); ?>
        <?php $_count = count($_items) ?>
        <?php $_index = 0; ?>
        <?php foreach ($_items as $_item): ?>
    <?php if ($_item->getOrderItem()->getParentItem()) continue; else $_index++ ?>
    <tbody class="<?php echo ($_index%2 ? 'even' : 'odd') ?>">
        <?php echo $this->getItemHtml($_item) ?>
    </tbody>
        <?php endforeach; ?>
    <tfoot>
        <tr>
            <td colspan="4" class="a-right"><?php echo $this->__('Order Subtotal') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_invoice->getSubtotal()) ?></td>
        </tr>
        <?php if ($_invoice->getDiscountAmount() > 0): ?>
            <tr>
                <td colspan="4" class="a-right"><?php echo $this->__('Discount :') ?></td>
                <td class="last a-right"><?php echo $_order->formatPrice(0.00 - $_invoice->getDiscountAmount()) ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_invoice->getTaxAmount() > 0): ?>
            <tr>
                <td colspan="4" class="a-right"><?php echo $this->__('Tax') ?></td>
                <td class="last a-right"><?php echo $_order->formatPrice($_invoice->getTaxAmount()) ?></td>
            </tr>
        <?php endif; ?>
        <?php if ($_invoice->getShippingAmount() || $_invoice->getShippingDescription()): ?>
            <tr>
                <td colspan="4" class="a-right"><?php echo $this->__('Shipping & Handling') ?></td>
                <td class="last a-right"><?php echo $_order->formatPrice($_invoice->getShippingAmount()) ?></td>
            </tr>
        <?php endif; ?>
        <tr>
            <td colspan="4" class="a-right"><?php echo $this->__('Grand Total') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_invoice->getGrandTotal()) ?></td>
        </tr>
    </tfoot>
</table>
<script type="text/javascript">decorateTable('my-orders-table-<?php echo $_invoice->getId(); ?>')</script>
<?php endforeach; ?>