<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */


/**
 * Super product options
 *
 * @see Mage_Catalog_Block_Product_View_Super_Config
 */
?>
<?php $_product = $this->getProduct() ?>
		
		<?php if($_product->isSaleable()): ?>
			<span class="product-price"><?php echo $this->helper('catalog/product')->getPriceHtml($_product) ?></span>
			<div class="product-attributes">
				<table cellspacing="0">
				<?php foreach($this->getAllowAttributes() as $_attribute): ?>
					<tr>
						<td class="label"><?php echo $_attribute->getLabel() ?>:</td>
						<td>
							<select name="super_attribute[<?php echo $_attribute->getAttributeId() ?>]" id="attribute<?php echo $_attribute->getAttributeId() ?>" class="required-entry super-attribute select super-attribute-select">
								<option><?php echo $this->__('Choose an Option...') ?></option>
							</select>
						</td>
					</tr>
				<?php endforeach; ?>
				</table>
				<input type="hidden" name="" id="" />
			</div>
		
			<?php $_tierPrices = $this->getTierPrices() ?>
			<?php if(count($_tierPrices)>0): ?>
			<div class="product-pricing">
				<ul class="bare">
				<?php foreach($_tierPrices as $_price): ?>
					<li><?php echo $this->__('Buy %s for %s each', $_price['price_qty'], $_price['formated_price']) ?>
					<?php if(($_product->getPrice() == $_product->getFinalPrice() && $_product->getPrice() > $_price['price'])
					|| ($_product->getPrice() != $_product->getFinalPrice() &&  $_product->getFinalPrice() > $_price['price'])): ?>
						<?php echo $this->__('and') ?> <strong><?php echo $this->__('save %s%%', $_price['savePercent']) ?>
					<?php endif ?></strong>
					</li>
				<?php endforeach ?>
				</ul>
			</div>
			<?php endif; ?>
		
			<p><small><strong><?php echo $this->__('Availability: In stock.') ?></strong></small></p>
		<?php else: ?>
			<p><small><strong><?php echo $this->__('Availability: Out of stock.') ?></strong></small></p>
		<?php endif; ?>

		<?php if($_product->isSaleable()): ?>
		<table>
			<tr>
				<td><label for="qty"><?php echo $this->__('Qty') ?>:</label></td>
				<td><input name="qty" type="text" class="input-text qty" id="qty" maxlength="12" value="<?php echo $this->getMinimalQty($_product) ?>" /></td>
				<td>&nbsp;<button class="form-button" onclick="productAddToCartForm.submit()"><span><?php echo $this->__('Add to Cart') ?></span></button></td>
			</tr>
		</table>
		<?php endif; ?>
	</div><div class="clear"></div>
</div><br />
<script type="text/javascript">
	var spConfig = new Product.Config(<?php echo $this->getJsonConfig() ?>);
</script>
