<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Grouped product data template
 *
 * @see Mage_Catalog_Block_Product_View_Media
 */
?>
<?php $_product = $this->getProduct() ?>
<?php $_associatedProducts = $this->getAssociatedProducts() ?>
		<h4><?php echo $this->__('Quick Overview') ?></h4>
        <div class="short-description"><?php echo nl2br($_product->getShortDescription()) ?></div>
		<?php if($_product->isSaleable() && count($_associatedProducts)): ?>
			<p><small><strong><?php echo $this->__('Availability: In stock.') ?></strong></small></p>
		<?php else: ?>
			<p><small><strong><?php echo $this->__('Availability: Out of stock.') ?></strong></small></p>
		<?php endif; ?>
	</div><div class="clear"></div>
</div>
<table cellspacing="0" class="shopping-cart product-data" id="super-product-table">
	<thead>
		<tr>
			<th><?php echo $this->__('Product Name') ?></th>
			<th class="a-right"><?php echo $this->__('Price') ?></th>
			<?php if ($_product->isSaleable()): ?>
			<th class="a-center"><?php echo $this->__('Qty') ?></th>
			<?php endif; ?>
		</tr>
	</thead>
	<tbody>
	<?php if (count($_associatedProducts)): ?>
	<?php foreach ($_associatedProducts as $_item): ?>
		<tr>
			<td><?php echo $this->htmlEscape($_item->getName()) ?></td>
			<td class="a-right">
				<?php $_price = $_item->getPrice() ?>
				<?php $_finalPrice = $_item->getFinalPrice() ?>
				<?php if ($_finalPrice == $_price): ?>
					<span class="nobr"><?php echo Mage::helper('core')->currency($_price) ?></span><br />
				<?php else: ?>
					<span class="nobr old-price"><?php echo $this->__('Price') ?>&nbsp;<?php echo Mage::helper('core')->currency($_price) ?></span><br />
					<span class="nobr special-price" style="font-size:12px;"><?php echo $this->__('Special Price') ?>&nbsp;<?php echo Mage::helper('core')->currency($_finalPrice) ?></span>
				<?php endif; ?>
				<?php if($_item->getTierPriceCount()): ?>
					<?php foreach ($_item->getFormatedTierPrice() as $_tierPrice): ?>
						<?php if($_tierPrice['price'] <= $_finalPrice): ?>
							<span class="nobr"><?php echo $this->__('Buy %s for %s', $_tierPrice['price_qty']*1, $_tierPrice['formated_price']) ?></span>
						<?php endif; ?>
					<?php endforeach; ?>
				<?php endif; ?>
			</td>
			<?php if ($_product->isSaleable()): ?>
			<td class="a-center">
			<?php if ($_item->isSaleable()) : ?>
				<input name="super_group[<?php echo $_item->getId() ?>]" value="<?php echo $_item->getQty()*1 ?>" type="text" class="input-text qty" />
			<?php else: ?>
				<?php echo $this->__('Out of stock.') ?>
			<?php endif; ?>
			</td>
			<?php endif; ?>
		</tr>
	<?php endforeach; ?>
	<?php else: ?>
	<tr>
		<td colspan="<?php if ($_product->isSaleable()): ?>4<?php else : ?>3<?php endif; ?>"><?php echo $this->__('No options of this product are available.') ?></td>
	</tr>
	<?php endif; ?>
	</tbody>
</table>
<?php if($_product->isSaleable() && count($_associatedProducts)): ?>
	<div class="col2-set">
		<div class="col-1">&nbsp;</div>
		<div class="col-2 a-right">
			<?php if($_product->isSaleable()): ?>
				<button class="form-button" onclick="productAddToCartForm.submit()"><span><?php echo $this->__('Add to Cart') ?></span></button>
			<?php endif; ?>&nbsp;
		</div><div class="clear"></div><br />
	</div>
<?php endif; ?>
<script type="text/javascript">decorateTable('super-product-table')</script>