<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<?php $_product=$this->getProduct() ?>
<div class="product-info-box">
    <div class="product-essential">
        <div class="product-shop">
			<form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form">
			<div class="col2-alt-set">
				<div class="col-1">
					<div class="product-image"><img src="<?php echo $this->helper('catalog/image')->init($_product, 'small_image')->resize(85, 85); ?>" width="85" height="85" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" /></div>
					<?php if($_product->isSaleable()): ?>
						<?php if ($this->helper('wishlist')->isAllow()) : ?>
							<div style="padding:7px 0 5px 8px;"><a href="<?php echo $this->helper('wishlist')->getAddUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a></div>
						<?php endif; ?>
					<?php endif; ?>
					<?php if ($this->canEmailToFriend()): ?>
						<div style="padding:0 0 5px 6px;"><a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a></div>
					<?php endif; ?>
				</div>
				<div class="col-2">
					<h3 class="product-name"><?php echo $this->htmlEscape($_product->getName()) ?></h3>
					<?php echo $this->getChildHtml('product_type_data') ?>
			
            <input type="hidden" name="product" value="<?php echo $_product->getId() ?>" />
            <input type="hidden" name="related_product" id="related-products-field" value="" />

            </form>

            <script type="text/javascript">
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function() {
                    if(this.validator.validate()) {
                        this.form.submit();
                    }
                }.bind(productAddToCartForm);
            </script>

            <div class="clear"></div>

			<div class="head">
                <h4><?php echo $this->__('Product Description') ?></h4>
            </div>
            <div class="product-specs"><?php echo nl2br($_product->getDescription()) ?></div>
			<?php if($_additional = $this->getAdditionalData()): ?>
			<div class="attribute-specs"><br />
				<h4><?php echo $this->__('Additional Information') ?></h4>
				<table cellspacing="0" class="data-table" id="product-attribute-specs-table">
					<?php foreach ($_additional as $_data): ?>
					<tr>
						<td class="label"><?php echo $_data['label'] ?></td>
						<td class="data"><?php echo $_data['value'] ?></td>
					</tr>
					<?php endforeach; ?>
				</table>
				<script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
			</div>
			<?php endif; ?>
			<?php echo $this->getChildHtml('upsell_products') ?>
			<?php echo $this->getChildHtml('product_additional_data') ?>
        </div>
    </div>
</div><div class="clear"></div>
<br /><br />