<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="in-page">
	<div class="page-head"><h3><?php echo $this->__('My Wishlist') ?></h3></div>
	<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
	<?php if($this->getWishlist()->getSize()): ?>
	<?php if($this->helper('wishlist')->isRssAllow()): ?>
		<p class="a-right"><a href="<?php echo $this->helper('wishlist')->getRssUrl(); ?>" class="link-feed"><?php echo $this->__('RSS Feed') ?></a></p>
	<?php endif; ?>
	<form action="<?php echo $this->getUrl('*/*/update') ?>" method="post">
		<table cellspacing="0" class="shopping-cart product-data" id="wishlist-table">
			<thead>
				<tr>
					<th><?php echo $this->__('Product') ?></th>
					<th><?php echo $this->__('Added') ?></th>
					<th class="a-center"><?php echo $this->__('Action') ?></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach($this->getWishlist() as $item): ?>
				<tr class="td-noborder">
					<td style="padding-top:15px;">
						<div><a href="<?php echo $item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($item, 'small_image')->resize(100, 100); ?>" alt="<?php echo $this->htmlEscape($item->getName()) ?>" width="100" /></a></div>
						<div><a href="<?php echo $item->getProductUrl() ?>" title="<?php echo $this->htmlEscape($item->getName()) ?>"><?php echo $this->htmlEscape($item->getName()) ?></a></div>
						<?php echo $this->helper('catalog/product')->getPriceHtml($item) ?>
					</td>
					<td class="a-center">
						<?php echo $this->getFormatedDate($item->getAddedAt()) ?>
					</td>
					<td class="a-center">
					<?php if($item->isSaleable()): ?>
						<a href="#" onclick="setLocation('<?php echo $this->getItemAddToCartUrl($item) ?>');return false;" class="link-cart"><?php echo $this->__('Add to Cart') ?></a><br />
					<?php endif; ?>
						<br /><a href="#" onclick="confirmRemoveWishlistItem('<?php echo $this->getItemRemoveUrl($item) ?>');return false;" class="link-remove" ><?php echo $this->__('Remove') ?></a>
					</td>
				</tr>
				<tr>
					<td colspan="3" style="padding-bottom:15px;">
						<?php echo $this->__('Comment') ?>:
						<textarea name="description[<?php echo $item->getWishlistItemId() ?>]" class="input-text" rows="3" cols="3" style="padding:3px;width:98%;height:40px;" onfocus="focusComment(this)" onblur="focusComment(this)"><?php echo ( $this->getEscapedDescription($item) ) ? $this->getEscapedDescription($item) : $this->helper('wishlist')->defaultCommentString() ?></textarea>
					</td>
				</tr>
			<?php endforeach ?>
			</tbody>
		</table>
		<script type="text/javascript">decorateTable('wishlist-table')</script>
		<div class="small-buttons a-center nobr">
			<button onclick="setLocation('<?php echo $this->getUrl('*/*/share') ?>')" class="form-button-alt" type="button"><span><?php echo $this->__('Share Wishlist') ?></span></button>
			<?php if($this->isSaleable()):?>
			<button onclick="setLocation('<?php echo $this->getUrl('*/*/allcart') ?>')" class="form-button-alt"  type="button"><span><?php echo $this->__('Add All to Cart') ?></span></button>
			<?php endif;?>
			<button type="submit" class="form-button" name="do"><span><?php echo $this->__('Update Wishlist') ?></span></button>
		</div>
	</form>
	<?php else: ?>
		<p><?php echo $this->__('You have no items in your wishlist.') ?></p>
	<?php endif ?>
	<br /><div class="button-set">
		<a href="<?php echo $this->getBackUrl() ?>" class="left">&laquo; <?php echo $this->__('Back') ?></a>
	</div><br /><br />
</div>
<script type="text/javascript">
	function confirmRemoveWishlistItem(url){
		if(confirm('<?php echo $this->__('Are you sure you want to remove this product from your wishlist?') ?>')) {
			setLocation(url);
		}
	}
	
	function focusComment(obj) {
		if( obj.value == '<?php echo $this->__('Please, enter your comments...') ?>' ) {
			obj.value = '';
		} else if( obj.value == '' ) {
			obj.value = '<?php echo $this->__('Please, enter your comments...') ?>';
		}
	}
</script>
