<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Rss
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head-container">
    <h2 class="page-head"><?php echo $this->__('RSS Feeds') ?></h2>
</div>
<?php 
$_categories = $this->getRssCatalogFeeds();
$_misc = $this->getRssMiscFeeds();
?>
    <?php if($_misc): ?>
    <table cellspacing="0" class="data-table" id="rss-table-misc">
        <thead><tr><th>Miscellaneous Feeds</th></tr></thead>
        <tbody>
    <?php foreach ($_misc as $_feed): ?>
            <tr>
                <td><span><?php echo $_feed->getLabel() ?></span><a href="<?php echo $_feed->getUrl() ?>"><?php echo $this->__('Get Feed'); ?></a></td>
            </tr>
    <?php endforeach; ?>
         </tbody>
    </table>
    <?php endif; ?>
    <?php if ($_categories || $_misc): ?><br/><?php endif ?>
    <?php if($_categories): ?>
    <table cellspacing="0" class="data-table" id="rss-table-category">
    <thead><tr><th>Category Feeds</th></tr></thead>
    <tbody>
    <?php foreach ($_categories as $_category): ?>
    <tr>
        <td><span><?php echo $_category->getLabel() ?></span><a href="<?php echo $_category->getUrl() ?>"><?php echo $this->__('Get Feed'); ?></a></td>
    </tr>
    <?php endforeach; ?>
    </tbody>
</table>
<script type="text/javascript">decorateTable('rss-table-misc'); decorateTable('rss-table-category')</script>
<?php else: ?>
<p><?php echo $this->__('There are no %s.',$this->__('Rss Feeds')); ?></p>
<?php endif; ?>
