<title>
	<?php echo htmlspecialchars(html_entity_decode($this->getTitle())) ?>
</title>
<meta id="viewport" name="viewport" content="width=320; initial-scale=1.0; maximum-scale=1.0; user-scalable=0;" />
<script type="text/javascript">
    var BLANK_URL = '<?php echo $this->helper('core/js')->getJsUrl('blank.html') ?>';
    var BLANK_IMG = '<?php echo $this->helper('core/js')->getJsUrl('spacer.gif') ?>';
</script>

<?php echo $this->getCssJsHtml() ?>
<?php echo $this->getChildHtml() ?>
