<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if(isset($poll)) : ?>

<script type="text/javascript">
    function validatePollAnswerIsSelected()
    {
        var options = $$('input.poll_vote');

        for( i in options ) {
            if( options[i].checked == true ) {
                return true;
            }
        }
        return false;
    }
</script>

<div class="box">
	<h3 class="box-head"><?php echo $this->__('Community Poll') ?></h3>
    <form id="pollForm" action="<?php echo $action ?>" method="post" onsubmit="return validatePollAnswerIsSelected();">
		<h4><?php echo $poll->getPollTitle(); ?></h4>
		<?php if( $poll_answers ): ?>
		<ol>
			<?php foreach( $poll_answers as $answer ): ?>
			<li>
				<input type="radio" name="vote" class="poll_vote" id="vote_<?php echo $answer->getId() ?>" value="<?php echo $answer->getAnswerId() ?>" />
				<label for="vote_<?php echo $answer->getId() ?>"><?php echo $answer->getAnswerTitle() ?></label>
			</li>
			<?php endforeach; ?>
		</ol>
		<?php endif; ?>
        <p class="actions"><button class="form-button" type="submit"><span><?php echo $this->__('Vote') ?></span></button></p>
    </form>
</div>
<?php endif; ?>