<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_optionsCollection = $this->getOptions() ?>
<?php if ($_optionsCollection->getSize()): ?>
<div class="clear"></div>
<fieldset>
    <div class="product-attributes custom-options">
        <table cellspacing="0" border="0" cellpadding="0" id="custom-options-table">
        <?php foreach($_optionsCollection as $_option): ?>
            <?php echo $this->getOptionHtml($_option) ?>
        <?php endforeach; ?>
        </table>
    <p class="required">* Required Fields</p>
    </div>
	<script type="text/javascript">decorateTable('custom-options-table')</script>
	<script>

    var optionFileUpload = {
        productForm : $('product_addtocart_form'),
        formAction : '',
        formElements : {},
        upload : function(element){
            this.formElements = this.productForm.getElementsBySelector('input', 'select', 'textarea', 'button');
            this.removeRequire(element.readAttribute('id').sub('option_', ''));

            template = '<iframe id="upload_target" name="upload_target" style="width:0;height:0;border:0px solid #fff;"></iframe>';

            new Insertion.After(
    			$('option_'+element.readAttribute('id').sub('option_', '')+'_uploaded_file'),
    			template
    		);

            this.formAction = this.productForm.action;
            this.productForm.action = '<?php echo $this->getUrl('*/product/upload') ?>option_id/'+element.readAttribute('id').sub('option_', '');
            this.productForm.target = 'upload_target';
            this.productForm.submit();
            this.productForm.target = '';
            this.productForm.action = this.formAction;
        },
        removeRequire : function(skipElementId){
            for(var i=0; i<this.formElements.length; i++){
                if (this.formElements[i].readAttribute('id') != 'option_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
                    this.formElements[i].disabled='disabled';
                }
            }
        },
        addRequire : function(skipElementId){
            for(var i=0; i<this.formElements.length; i++){
                if (this.formElements[i].readAttribute('name') != 'options_'+skipElementId+'_file' && this.formElements[i].type != 'button') {
                    this.formElements[i].disabled='';
                }
            }
        },
        uploadCallback : function(data){
            this.addRequire(data.optionId);
            $('upload_target').remove();

            if (data.error) {

            } else {
                $('option_'+data.optionId+'_uploaded_file').value = data.fileName;
                $('option_'+data.optionId+'_file').value = '';
                $('option_'+data.optionId+'_file').hide();
                $('option_'+data.optionId+'').hide();
//popWin('http://192.168.0.191/dev/ruslan.voitenko/magento/index.php/catalog/product/gallery/id/16/image/126/', 'gallery', 'scrollbars=yes,width=300,height=300,resizable=yes');return false;
                template = '<div id="option_'+data.optionId+'_file_box"><a href="#"><img src="http://192.168.0.191/dev/ruslan.voitenko/magento/var/options/'+data.fileName+'"></a><a href="#" onclick="optionFileUpload.removeFile('+data.optionId+')">Remove file</a>';

                new Insertion.After(
        			$('option_'+data.optionId+'_uploaded_file'),
        			template
        		);
            }
        },
        removeFile : function(optionId)
        {
            $('option_'+optionId+'_uploaded_file').value= '';
            $('option_'+optionId+'_file').show();
            $('option_'+optionId+'').show();

            $('option_'+optionId+'_file_box').remove();
        }
    }
</script>
</fieldset>
<?php endif; ?>