<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<div class="box">
        <h3 class="box-head"><?php echo $this->__('Your Checkout Progress') ?></h3>
    <ol>
    <?php if($this->getCheckout()->getStepData('billing', 'complete')): ?>
        <li>
            <h4 class="complete"><?php echo $this->__('Billing Address') ?><span> | </span><a href="#billing" onclick="checkout.accordion.openSection('opc-billing');return false;"><?php echo $this->__('Change Billing Address') ?></a></h4>
            <address><?php echo $this->getBilling()->format('html') ?></address>
        </li>
    <?php else: ?>
        <li>
            <h4><?php echo $this->__('Billing Address') ?></h4>
        </li>
    <?php endif ?>

    <?php if($this->getCheckout()->getStepData('shipping', 'complete')): ?>
        <li>
            <h4 class="complete"><?php echo $this->__('Shipping Address') ?><span> | </span><a href="#payment" onclick="checkout.accordion.openSection('opc-shipping');return false;"><?php echo $this->__('Change Shipping Address') ?></a></h4>
            <address><?php echo $this->getShipping()->format('html') ?></address>
        </li>
    <?php else: ?>
        <li>
            <h4><?php echo $this->__('Shipping Address') ?></h4>
        </li>
    <?php endif ?>

    <?php if($this->getCheckout()->getStepData('shipping_method', 'complete')): ?>
        <li>
            <h4 class="complete"><?php echo $this->__('Shipping Method') ?><span> | </span><a href="#shipping_method" onclick="checkout.accordion.openSection('opc-shipping_method');return false;"><?php echo $this->__('Change Shipping Method') ?></a></h4>		
            <?php if ($this->getShippingMethod()): ?>
                <?php echo $this->getShippingDescription() ?>: <?php echo $this->getShippingAmount() ?>
            <?php else: ?>
                <p><?php echo $this->__('Shipping method has not been selected yet') ?></p>
            <?php endif ?>
        </li>
    <?php else: ?>
        <li>
            <h4><?php echo $this->__('Shipping Method') ?></h4>
        </li>
    <?php endif ?>

    <?php if($this->getCheckout()->getStepData('payment', 'complete')): ?>
        <li>
            <h4 class="complete"><?php echo $this->__('Payment Method') ?><span> | </span><a href="#payment" onclick="checkout.accordion.openSection('opc-payment');return false;"><?php echo $this->__('Change Payment Method') ?></a></h4>
            <?php echo $this->getPaymentHtml() ?>
        </li>
    <?php else: ?>
        <li>
            <h4><?php echo $this->__('Payment Method') ?></h4>
        </li>
    <?php endif ?>
    </ol>
</div>