<?php  $_order = $this->getOrder() ?>

<div class="page-head-container">
    <h2 class="page-head"><?php echo $this->__('Order #%s - %s', $_order->getRealOrderId(), $_order->getStatusLabel()) ?></h2>
    <?php if($this->helper('rss/order')->isStatusNotificationAllow()): ?>
        <a href="<?php echo $this->helper('rss/order')->getStatusHistoryRssUrl($_order) ?>" class="link-feed"><?php echo $this->__('Subscribe to Order Status') ?></a>
        <span> | </span>
    <?php endif; ?>
    <?php if ($this->helper('sales/reorder')->canReorder($_order)) : ?>
        <a href="<?php echo $this->getReorderUrl($_order) ?>"><?php echo $this->__('Reorder') ?></a>
        <span> | </span>
    <?php endif ?>
    <a href="<?php echo $this->getPrintUrl($_order) ?>" onclick="this.target='_blank'"><?php echo $this->__('Print Order') ?></a>
</div>
<?php echo $this->getStatusHistoryRssUrl($_order) ?>
<div class="box">
	<div>
		<h3><?php echo $this->__('About This Order:') ?></h3>
		<ul>
		  <?php $_links = $this->getLinks(); ?>
		    <?php foreach ($_links as $_link): ?>
		      <?php if($_link->getUrl()): ?>
		        <li><a href="<?php echo $_link->getUrl() ?>"><?php echo $_link->getLabel() ?></a></li>
		      <?php else: ?>
		        <li><strong><?php echo $_link->getLabel() ?></strong></li>
		      <?php endif; ?>
		    <?php endforeach; ?>
		</ul>
	</div>


	<p><?php echo $this->__('Order Date: %s', $this->formatDate($_order->getCreatedAt(), 'long')) ?></p>
	<div class="col2-set">
	    <div class="col-1">
	        <h3><?php echo $this->__('Shipping Address') ?></h3>
	        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
	    </div>
	    <div class="col-2">
	        <h3><?php echo $this->__('Shipping Method') ?><?php /* | <a href="#"><?php echo $this->__('Track Order') ?></a>*/ ?></h3>
	        <?php echo $_order->getShippingDescription() ?>
	    </div>
	</div>
	<div class="col2-set">
	    <div class="col-1">
	        <h3><?php echo $this->__('Billing Address') ?></h3>
	        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
	    </div>
	    <div class="col-2">
	        <h3><?php echo $this->__('Payment Method') ?></h3>
	        <?php echo $this->getPaymentInfoHtml() ?>
	    </div>
	</div>
</div>	