<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_item = $this->getItem() ?>
<?php $items = array_merge(array($_item), $_item->getChildrenItems()); ?>
<?php $_count = count ($items) ?>
<?php $_index = 0 ?>

<?php $bundleOptions = $this->getBundleOptions() ?>
<?php $_prevOptionLabel = '' ?>

<?php if($this->getOrderOptions() || $_item->getDescription() || $this->canDisplayGiftmessage()): ?>
    <?php $_showlastRow = true ?>
<?php else: ?>
    <?php $_showlastRow = false ?>
<?php endif; ?>

<?php foreach ($items as $_item): ?>
    <?php $this->setPriceDataObject($_item) ?>
    <?php if (empty($_option['value'])): ?>
        <?php $_option = array_shift($bundleOptions); ?>
    <?php endif; ?>
    <?php if ($_item->getParentItem()): ?>
        <?php if ($_prevOptionLabel != $_option['label']): ?>
        <tr>
            <td class="giftmessage-single-item indent">
                <strong><?php echo $_option['label'] ?></strong>
            </td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td>&nbsp;</td>
            <td class="last"></td>
        </tr>
        <?php $_prevOptionLabel = $_option['label'] ?>
        <?php endif; ?>
    <?php endif; ?>
    <tr class="<?php echo (++$_index==$_count && !$_showlastRow)?'border':'' ?>">
        <?php if (!$_item->getParentItem()): ?>
        <td>
            <div><?php echo $this->htmlEscape($_item->getName()) ?></div>
            <div class="nobr"><strong><?php echo $this->helper('sales')->__('SKU') ?>:</strong> <?php echo $_item->getSku() ?></div>
        </td>
        <?php else: ?>
        <td class="indent">
            <?php echo $this->getValueHtml(array_shift($_option['value']), $_item)?>
        </td>
        <?php endif; ?>
        <td>
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $_item->getStatus() ?>
            <?php endif; ?>
        </td>
        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('original_price') ?>
            <?php endif; ?>
        </td>
        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <?php echo $this->helper('tax')->__('Excl. Tax'); ?>
                    <?php endif; ?>
                    <?php echo $this->displayPriceAttribute('price') ?>
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <br />
                        <?php echo $this->helper('tax')->__('Incl. Tax'); ?>
                    <?php endif; ?>
                    <?php echo $this->displayPriceInclTax($_item); ?>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <td>
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <table cellpadding="0" cellspacing="0" width="100%" class="inline-table">
                    <tr>
                        <td><?php echo Mage::helper('sales')->__('Ordered') ?></td>
                        <td><?php echo $_item->getQtyOrdered()*1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyInvoiced()): ?>
                    <tr>
                        <td><?php echo Mage::helper('sales')->__('Invoiced') ?></td>
                        <td><?php echo $_item->getQtyInvoiced()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyShipped() && $this->isShipmentSeparately($_item)): ?>
                    <tr>
                        <td><?php echo Mage::helper('sales')->__('Shipped') ?></td>
                        <td><?php echo $_item->getQtyShipped()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyRefunded()): ?>
                    <tr>
                        <td><?php echo Mage::helper('sales')->__('Refunded') ?></td>
                        <td><?php echo $_item->getQtyRefunded()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                    <?php if ((float) $_item->getQtyCanceled()): ?>
                    <tr>
                        <td><?php echo Mage::helper('sales')->__('Canceled') ?></td>
                        <td><?php echo $_item->getQtyCanceled()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php elseif ($this->isShipmentSeparately($_item)): ?>
                <table cellpadding="0" cellspacing="0" width="100%" class="inline-table">
                    <tr>
                        <td><?php echo Mage::helper('sales')->__('Ordered') ?></td>
                        <td><?php echo $_item->getQtyOrdered()*1 ?></td>
                    </tr>
                    <?php if ((float) $_item->getQtyShipped()): ?>
                    <tr>
                        <td><?php echo Mage::helper('sales')->__('Shipped') ?></td>
                        <td><?php echo $_item->getQtyShipped()*1 ?></td>
                    </tr>
                    <?php endif; ?>
                </table>
            <?php endif; ?>
        </td>

        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php if ($this->helper('tax')->displayCartPriceExclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <?php echo $this->helper('tax')->__('Excl. Tax'); ?>
                    <?php endif; ?>
                    <?php echo $this->displayPriceAttribute('row_total') ?>
                <?php endif; ?>
                <?php if ($this->helper('tax')->displayCartPriceInclTax() || $this->helper('tax')->displayCartBothPrices()): ?>
                    <?php if ($this->helper('tax')->displayCartBothPrices()): ?>
                        <br />
                        <?php echo $this->helper('tax')->__('Incl. Tax'); ?>
                    <?php endif; ?>
                    <?php echo $this->displaySubtotalInclTax($_item); ?>
                <?php endif; ?>
            <?php endif; ?>
        </td>
        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('tax_amount') ?>
            <?php endif; ?>
        </td>

        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayTaxPercent($_item) ?>
            <?php endif; ?>
        </td>
        <td class="price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPriceAttribute('discount_amount') ?>
            <?php endif; ?>
        </td>
        <td class="last price">
            <?php if ($this->canShowPriceInfo($_item)): ?>
                <?php echo $this->displayPrices(
                    $_item->getBaseRowTotal() - $_item->getBaseDiscountAmount() + $_item->getBaseTaxAmount(),
                    $_item->getRowTotal() - $_item->getDiscountAmount() + $_item->getTaxAmount()
                ); ?>
            <?php endif; ?>
        </td>
    </tr>
<?php endforeach; ?>
<?php if($_showlastRow): ?>
    <tr <?php if (!$this->canDisplayGiftmessage()) echo 'class="border"' ?>>
        <td class="giftmessage-single-item indent">
            <div class="item-text">
                <?php if ($this->getOrderOptions()): ?>
                    <ul class="item-options-bundle">
                    <?php foreach ($this->getOrderOptions() as $option): ?>
                        <li><strong><?php echo $option['label'] ?>:</strong><br />
                            <?php echo $this->htmlEscape($option['value']); ?>
                        </li>
                    <?php endforeach; ?>
                    </ul>
                <?php endif; ?>
                <?php echo $_item->getDescription() ?>
            </div>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last"></td>
    </tr>
    <?php if ($this->canDisplayGiftmessage()): ?>
    <tr class="border">
        <td class="giftmessage-single-item">
            <?php if ($this->canDisplayContainer()): ?>
            <div id="<?php echo $this->getHtmlId() ?>" class="item-container f-left">
            <?php endif; ?>
            <div class="item-text">
                <div>
                    <a class="action-link" href="#" onclick="return giftMessagesController.toogleGiftMessage('<?php echo $this->getHtmlId() ?>')">
                    <span class="default-text">
                        <span class="add" <?php if($this->getMessage()->getId()): ?> style="display:none;"<?php endif;?>><?php echo $this->helper('sales')->__('Add Gift Messsage') ?></span>
                        <span class="edit" <?php if(!$this->getMessage()->getId()): ?> style="display:none;"<?php endif;?>><?php echo $this->helper('sales')->__('Edit Gift Messsage') ?></span>
                    </span>
                    <span class="close-text" style="display:none">
                        <?php echo $this->helper('sales')->__('Save and Close Message') ?>
                    </span>
                    </a>
                </div>
            </div>
            <div class="gift-form" style="display:none;" id="<?php echo $this->getFieldId('edit') ?>">
            <form id="<?php echo $this->getFieldId('form') ?>" action="<?php echo $this->getSaveUrl() ?>">
                <div class="entry-edit">
                    <fieldset>
                        <input type="hidden" id="<?php echo $this->getFieldId('type') ?>" name="<?php echo $this->getFieldName('type') ?>" value="order_item"/>
                        <span class="field-row f-left">
                            <label><?php echo $this->helper('sales')->__('From Name') ?></label><br />
                            <input class="input-text" type="text" id="<?php echo $this->getFieldId('sender') ?>" name="<?php echo $this->getFieldName('sender') ?>" value="<?php echo $this->htmlEscape($this->getMessage()->getSender()) ?>"/>
                        </span>
                        <span class="field-row f-left last">
                            <label><?php echo $this->helper('sales')->__('To Name') ?></label><br />
                            <input class="input-text" type="text" id="<?php echo $this->getFieldId('recipient') ?>" name="<?php echo $this->getFieldName('recipient') ?>"  value="<?php echo $this->htmlEscape($this->getMessage()->getRecipient()) ?>"/>
                        </span>
                        <div class="clear"></div>
                        <span class="field-row">
                            <label><?php echo $this->helper('sales')->__('Gift Message') ?></label><br />
                            <textarea class="input-text" id="<?php echo $this->getFieldId('message') ?>" onchange="giftMessagesController.toogleRequired('<?php echo $this->getFieldId('message') ?>', ['<?php echo $this->getFieldId('sender') ?>','<?php echo $this->getFieldId('recipient') ?>']);" name="<?php echo $this->getFieldName('message') ?>"><?php echo $this->htmlEscape($this->getMessage()->getMessage()) ?></textarea>
                        </span>
                    </fieldset>
                </div>
            </form>
            </div>
            <?php if ($this->canDisplayContainer()): ?>
            </div>
            <?php endif ?>
        </td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td class="last"></td>
    </tr>
    <?php endif; ?>
<?php endif; ?>
