<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($this->getItems()->getSize()): ?>
<div class="box">
    <h3 class="box-head"><?php echo $this->__('Cross-sell Products') ?></h3>
    <ol id="cross-sell-products">
     <?php foreach($this->getItems() as $_item): ?>
        <li>
            <a  class="product-image" href="<?php echo $_item->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($_item, 'thumbnail')->resize(38) ?>" alt="<?php echo $this->htmlEscape($_item->getName()) ?>" width="38" height="38" /></a>
            <div class="product-details">
                <a href="<?php echo $_item->getProductUrl() ?>"><?php echo $this->htmlEscape($_item->getName()) ?></a>
                <?php echo $this->getPriceHtml($_item) ?>
                <a href="<?php echo $this->getAddToCartUrl($_item) ?>"><?php echo $this->__('Add to Cart') ?></a>
                <?php if ($this->helper('wishlist')->isAllow()) : ?>
                <a href="<?php echo $this->getAddToWishlistUrl($_item) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
                <?php endif; ?>
            </div>
        </li>
    <?php endforeach; ?>
    </ol>
    <script type="text/javascript">decorateList('cross-sell-products')</script>
</div>
<?php endif ?>
