<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="header-top">
	<div id="logo">
		<a href="<?php echo $this->getUrl('') ?>"><img src="<?php echo $this->getLogoSrc() ?>" alt="<?php echo $this->getLogoAlt() ?>" /></a>
		<h1>Magento - Open Source eCommerce</h1>
	</div>
	<p><strong><?php echo $this->htmlEscape($this->getWelcome()) ?></strong></p>
	<?php echo $this->getChildHtml('topLinks') ?>
	<?php echo $this->getChildHtml('topSearch') ?>
	<?php echo $this->getChildHtml('store_language') ?>
</div>	
<?php echo $this->getChildHtml('topMenu') ?>