<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

/**
 * Product view template
 *
 * @see Mage_Catalog_Block_Product_View
 */
?>
<div class="padder">
<div id="messages_product_view"><?php echo $this->getMessagesBlock()->getGroupedHtml() ?></div>
<?php $_product=$this->getProduct() ?>
        <div class="product-img-box">
            <?php echo $this->getChildHtml('media') ?>
        </div>

        <div class="product-info-box">
            <h3 class="product-name"><?php echo $this->htmlEscape($_product->getName()) ?></h3>

            <?php if ($this->canEmailToFriend()): ?>
                <a href="<?php echo $this->helper('catalog/product')->getEmailToFriendUrl($_product) ?>"><?php echo $this->__('Email to a Friend') ?></a><br />
            <?php endif; ?>

            <?php echo $this->helper('review/product')->getSummaryHtml($_product, null, 1) ?>

            <form action="<?php echo $this->getAddToCartUrl($_product) ?>" method="post" id="product_addtocart_form">
                <fieldset>
                <input type="hidden" name="product" value="<?php echo $_product->getId() ?>"/>
                <input type="hidden" name="related_product" id="related-products-field" value=""/>
                </fieldset>
                <?php echo $this->getChildHtml('alert_urls') ?>
                <?php echo $this->getChildHtml('product_type_data') ?>
            </form>

            <script type="text/javascript">
                var productAddToCartForm = new VarienForm('product_addtocart_form');
                productAddToCartForm.submit = function() {
                    if(this.validator.validate()) {
                        this.form.submit();
                    }
                }.bind(productAddToCartForm);
            </script>

            <div class="clear"></div>
            <br/>
            <h4 class="border-head"><?php echo $this->__('Quick Overview') ?></h4>
            <div class="short-description"><?php echo nl2br($_product->getShortDescription()) ?></div>

        </div>
        <div class="clear"></div>
</div>
<br/><br/>
<?php $_upsellHtml = $this->getChildHtml('upsell_products') ?>
<ul class="tabs">
    <li id="product_tabs_description" class="active first"><a href="#">Product Description</a></li>
    <?php if ($_upsellHtml!=''): ?><li id="product_tabs_upsell"><a href="#">We Also Recommend</a></li><?php endif ?>
    <li id="product_tabs_tags"><a href="#">Product Tags</a></li>
    <?php if($_additional = $this->getAdditionalData()): ?><li id="product_tabs_additional"><a href="#">Additional Information</a></li><?php endif?>
</ul>
<div class="padder">
    <div id="product_tabs_description_contents" class="product-specs"><?php echo nl2br($_product->getDescription()) ?></div>
    <?php if ($_upsellHtml): ?><div id="product_tabs_upsell_contents"><?php echo $_upsellHtml ?></div><?php endif ?>
    <div id="product_tabs_tags_contents"><?php echo $this->getChildHtml('product_tag_list') ?></div>
    
    <?php if($_additional = $this->getAdditionalData()): ?>
    <div id="product_tabs_additional_contents" class="collateral-box attribute-specs">
        <table cellspacing="0" class="data-table" id="product-attribute-specs-table">
        <?php foreach ($_additional as $_data): ?>
        <tr>
            <td class="label"><?php echo $_data['label'] ?></td>
            <td class="data"><?php echo $_data['value'] ?></td>
        </tr>
        <?php endforeach; ?>
        </table>
        <script type="text/javascript">decorateTable('product-attribute-specs-table')</script>
        </div>
    <?php endif;?>
</div>
<script type="text/javascript">
Varien.Tabs = Class.create();
Varien.Tabs.prototype = {
  initialize: function(selector) {
    var self=this;
    $$(selector+' a').each(this.initTab.bind(this));
  },

  initTab: function(el) {
      el.href = 'javascript:void(0)';
      if ($(el.parentNode).hasClassName('active')) {
        this.showContent(el);
      }
      el.observe('click', this.showContent.bind(this, el));
  },

  showContent: function(a) {
    var li = $(a.parentNode), ul = $(li.parentNode);
    ul.getElementsBySelector('li', 'ol').each(function(el){
      var contents = $(el.id+'_contents');
      if (el==li) {
        el.addClassName('active');
        contents.show();
      } else {
        el.removeClassName('active');
        contents.hide();
      }
    });
  }
}
new Varien.Tabs('.tabs')</script>
