<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php $_order = $this->getOrder() ?>
<h3><?php echo $this->__('Order #%s', $_order->getRealOrderId()) ?></h3>
<div class="divider"></div>
<div class="col2-set">
    <?php if (!$_order->getIsVirtual()): ?>
    <div class="col-1">
        <h4><?php echo $this->__('Shipping Address') ?></h4>
        <address><?php echo $_order->getShippingAddress()->format('html') ?></address>
    </div>
    <div class="col-2">
    <?php else: ?>
    <div class="col-1">
    <?php endif; ?>

        <h4><?php echo $this->__('Billing Address') ?></h4>
        <address><?php echo $_order->getBillingAddress()->format('html') ?></address>
    </div>
<?php if (!$_order->getIsVirtual()): ?>
</div>
<br />
<div class="col2-set">
    <div class="col-1">
        <h4><?php echo $this->__('Shipping Method') ?></h4>
         <?php echo $_order->getShippingDescription() ?>
    </div>
<?php endif; ?>
    <div class="col-2">
        <h4><?php echo $this->__('Payment Method') ?></h4>
        <?php echo $this->getPaymentInfoHtml() ?>
    </div>
</div>
<br />
<h4><?php echo $this->__('Items Ordered') ?></h4>
<table cellspacing="0" class="data-table">
    <thead>
        <tr>
            <th><?php echo $this->__('Product Name') ?></th>
            <th class="a-right" width="15%"><?php echo $this->__('Price') ?></th>
            <th class="a-center" width="10%"><?php echo $this->__('Qty Ordered') ?></th>
            <?php if (!$_order->getIsVirtual()): ?><th class="a-center" width="10%"><?php echo $this->__('Qty Shipped') ?></th><?php endif; ?>
            <th class="a-right last" width="20%"><?php echo $this->__('Subtotal') ?></th>
        </tr>
    </thead>
    <tbody>
        <?php $_items = $_order->getItemsCollection(); ?>
        <?php $_count = $_items->count(); ?>
        <?php $_index = 0; ?>
        <?php foreach ($_items as $_item): ?>
            <tr<?php echo ($_index++ > $_count ? ' class="last"' : '') ?>>
            <td>
                <?php echo $this->htmlEscape($_item->getName()) ?>
                <?php echo $_item->getDescription() ?>
            </td>
            <td class="a-right nowrap"><?php echo $_order->formatPrice($_item->getPrice()) ?></td>
            <td class="a-center"><?php echo $_item->getQtyOrdered()*1 ?></td>
            <?php if (!$_order->getIsVirtual()): ?><td class="a-center"><?php echo $_item->getQtyShipped()*1 ?></td><?php endif; ?>
            <td class="last a-right nowrap"><?php echo $_order->formatPrice($_item->getRowTotal()) ?></td>
        <?php endforeach; ?>
        </tr>
    </tbody>
    <?php if ($_order->getIsVirtual()): $colspan = 3; else: $colspan = 4; endif; ?>
    <tfoot>
        <tr>
            <td colspan="<?php echo $colspan; ?> " class="a-right"><?php echo $this->__('Order Subtotal') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_order->getSubtotal()) ?></td>
        </tr>
        <?php if ($_order->getDiscountAmount() > 0): ?>
        <tr>
            <td colspan="<?php echo $colspan; ?>" class="a-right"><?php echo $this->__('Discount :') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice(0.00 - $_order->getDiscountAmount()) ?></td>
        </tr>
        <?php endif; ?>
        <?php if ($_order->getTaxAmount() > 0): ?>
        <tr>
            <td colspan="<?php echo $colspan; ?>" class="a-right"><?php echo $this->__('Tax') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_order->getTaxAmount()) ?></td>
        </tr>
        <?php endif; ?>
        <?php if (!$_order->getIsVirtual() && ($_order->getShippingAmount()*1 || $_order->getShippingDescription())): ?>
        <tr>
            <td colspan="<?php echo $colspan; ?>" class="a-right"><?php echo $this->__('Shipping & Handling') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_order->getShippingAmount()) ?></td>
        </tr>
        <?php endif; ?>
        <tr>
            <td colspan="<?php echo $colspan; ?>" class="a-right"><?php echo $this->__('Grand Total') ?></td>
            <td class="last a-right"><?php echo $_order->formatPrice($_order->getGrandTotal()) ?></td>
        </tr>
    </tfoot>
</table>
<script type="text/javascript">window.print();</script>