<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if( $this->getCount() ): ?>
<br /><div class="head"><h4><?php echo $this->__('Product Tags') ?></h4></div>
	<div class="tags-list">
		<?php $_iterator = 0; ?>
		<?php foreach( $this->getTags() as $_tag ): ?>
			<?php $_iterator += 1; ?>
			<a href="<?php echo $_tag->getTaggedProductsUrl() ?>"><?php echo $this->htmlEscape($_tag->getName()) ?></a> (<?php echo $_tag->getPopularity() ?>)
			<?php if($_iterator != $this->getCount()): ?>, <?php endif; ?>
		<?php endforeach; ?>
	</div>
<?php endif; ?>