<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

<?php $_option = $this->getOption() ?>
<?php $_selections = $_option->getSelections() ?>
<tr>
    <td class="label"><?php echo $this->htmlEscape($_option->getTitle()) ?></td>
    <td>
        <?php if (count($_selections) == 1 && $_selections[0]->getDefault()): ?>
            <?php echo $_selections[0]->getName() ?>
            <input type="hidden" name="bundle_option[<?php echo $_option->getId() ?>][]" value="<?php echo $_selections[0]->getSelectionId() ?>" />
        <?php else:?>
            <select onchange="bundle.changeSelection(this)" multiple="multiple" id="bundle-option-<?php echo $_option->getId() ?>" name="bundle_option[<?php echo $_option->getId() ?>]" class="<?php if ($_option->getRequired()) echo 'required-entry ' ?>select bundle-option-select">
                <option value=""><?php echo $this->__('None') ?></option>
                <?php foreach($_selections as $_selection): ?>
                    <option value="<?php echo $_selection->getSelectionId() ?>"<?php echo ($_selection->getIsDefault() && $_selection->isSaleable())?' selected="selected" ':'' ?><?php echo !$_selection->isSaleable()?' disabled="disabled" ':'' ?>><?php echo $this->getSelectionQtyTitlePrice($_selection) ?></option>
                <?php endforeach;?>
            </select>
        <?php endif; ?>
    </td>
    <td valign="top" class="a-center">&nbsp;</td>
</tr>