<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage_Bundle
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */

?>

		<?php $_product = $this->getProduct() ?>
		<?php if($_product->isSaleable()): ?>
		<script type="text/javascript">
			var bundle = new Product.Bundle(<?php echo $this->getJsonConfig() ?>);
		</script>
			<p><small><strong><?php echo $this->__('Availability: In stock.') ?></strong></small></p>
		<?php else: ?>
			<p><small><strong><?php echo $this->__('Availability: Out of stock.') ?></strong></small></p>
		<?php endif; ?>
		
		<span class="product-bundle-price"><?php echo $this->getPriceHtml($_product) ?></span>
		<span class="product-price"><?php echo $this->getChildHtml('bundle_prices') ?></span>
	</div><div class="clear"></div>
</div>
