<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>

<?php if ($_products = $this->getRecentlyComparedProducts()): ?>
<div class="box">
<h3 class="box-head"><?php echo $this->__('Your Recently Compared') ?></h3>
<table cellspacing="0" class="recently-list" id="recently-compared-list-table">
<tr>
<?php $i=0; foreach ($_products as $_product): ?>
    <?php if ($i>5): continue; endif; ?>

    <td>
		<a class="product-image" href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>">
			<img src="<?php echo $_product->getSmallImageUrl() ?>" width="80" height="77" alt="<?php echo $this->htmlEscape($_product->getName()) ?>" />
		</a>
		<h4 class="product-name"><a href="<?php echo $_product->getProductUrl() ?>" title="<?php echo $this->htmlEscape($_product->getName()) ?>)"><?php echo $this->htmlEscape($_product->getName()) ?></a></h4>
		<?php echo $this->getReviewsSummaryHtml($_product, 'short') ?>
		<?php echo $this->getPriceHtml($_product) ?>
		<?php if($_product->isSaleable()): ?>
		<button class="form-button" onclick="setLocation('<?php echo $this->getAddToCartUrl($_product) ?>')"><span><?php echo $this->__('Add to Cart') ?></span></button>
		<?php else: ?>
		<p><small><?php echo $this->__('Out of stock') ?></small></p>
		<?php endif; ?>
		<p>
			<?php if ($this->helper('wishlist')->isAllow()) : ?>
			<a href="<?php echo $this->getAddToWishlistUrl($_product) ?>"><?php echo $this->__('Add to Wishlist') ?></a>
			<?php endif; ?>
			<?php if($_compareUrl=$this->getAddToCompareUrl($_product)): ?><br />
			<a href="<?php echo $_compareUrl ?>"><?php echo $this->__('Add to Compare') ?></a>
			<?php endif; ?>
		</p>
	</td>
<?php $i++; endforeach; ?>
<?php for($i;$i%5!=0;$i++): ?>
        <td>&nbsp;</td>
    <?php endfor ?>
    </tr>
</table></div>
<?php endif; ?>