<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2004-2007 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php if($this->getProductData()->getId()): ?>
    <div class="page-head-container">
        <h2 class="page-head"><?php echo $this->__('Review Details') ?></h2>
    </div>
	<div>
		<a class="product-image" href="<?php echo $this->getProductData()->getProductUrl() ?>"><img src="<?php echo $this->helper('catalog/image')->init($this->getProductData(), 'small_image')->resize(125, 125); ?>" alt="<?php echo $this->htmlEscape($this->getProductData()->getName()) ?>" height="100" width="100" /></a>
		<?php if( $this->getRating() && $this->getRating()->getSize()): ?>
		  <p><small><?php echo $this->__('Average Customer Rating') ?>:</small></p>
		  <?php echo $this->helper('review/product')->getSummaryHtml($this->getProductData()) ?>
		<?php endif; ?>
	</div>
    <div>
        <h3 class="product-name"><?php echo $this->htmlEscape($this->getProductData()->getName()) ?></h3>
        <?php if( $this->getRating() && $this->getRating()->getSize()): ?>
        <p><strong><?php echo $this->__('Product Rating:') ?></strong></p>
            <?php foreach ($this->getRating() as $_rating): ?>
            <?php if($_rating->getPercent()): ?>
                <div class="ratings">
                   <?php echo $this->__($_rating->getRatingCode()) ?>
                    <div class="rating-box">
                        <div class="rating" style="width:<?php echo ceil($_rating->getPercent()) ?>%;"></div>
                    </div>
                </div>
            <?php endif; ?>
            <?php endforeach; ?>
        <?php endif; ?>
        <p><?php echo $this->__('Product Review (submitted on %s):', $this->dateFormat($this->getReviewData()->getCreatedAt())) ?></p>
        <p><?php echo nl2br($this->htmlEscape($this->getReviewData()->getDetail())) ?></p>
    </div>
    <div class="buttons-container"><a href="<?php echo $this->getBackUrl() ?>" class="back-link">&laquo; <?php echo $this->__('Back to Product Reviews') ?></a></div>
<?php endif; ?>
