<?php
/**
 * Magento
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to license@magentocommerce.com so we can send you a copy immediately.
 *
 * @category   design_default
 * @package    Mage
 * @copyright  Copyright (c) 2008 Irubin Consulting Inc. DBA Varien (http://www.varien.com)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<div class="page-head-container">
    <h2 class="page-head"><?php echo $this->__('Change Billing Address') ?></h2>
    <button class="form-button" onclick="setLocation('<?php echo $this->getAddNewUrl() ?>')"><span><?php echo $this->__('Add New Address') ?></span></button>
</div>
<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
<div class="box">
<?php $_index=0 ?>
<?php foreach ($this->getAddressCollection() as $_address): ?>
    <?php if($_index%3==0): ?><div class="col3-set"><?php endif; ?>
    <div class="col-<?php echo ($_index%3+1) ?>">
            <p class="actions">
                <a href="<?php echo $this->getEditAddressUrl($_address) ?>"><?php echo $this->__('Edit Address') ?></a><span> | </span>
                <a href="<?php echo $this->getSetAddressUrl($_address) ?>"><strong><?php echo $this->__('Select Address') ?></strong></a>
            </p>
            <address>
                <?php echo $_address->format('html') ?>
                <?php if($this->isAddressDefaultBilling($_address)): ?>
                <br/><strong><?php echo $this->__('Default Billing') ?></strong>
                <?php endif; ?>
                <?php if($this->isAddressDefaultShipping($_address)): ?>
                <br/><strong><?php echo $this->__('Default Shipping') ?></strong>
                <?php endif; ?>
            </address>
    </div>
    <?php if($_index && $_index%3==0): ?></div><br/><?php endif; ?>
<?php $_index++ ?>
<?php endforeach; ?>
<?php if(!$_index || $_index%3!=0): ?></div><br/><?php endif; ?>
</div>
<div class="buttons-container">
    <a href="<?php echo $this->getBackUrl() ?>" class="back-link"><?php echo $this->__('&laquo; Back to Billing Information') ?></a>
</div>
